image: node:7.0.0
pipelines:
  clone:
    depth: full
  default:
    - step:
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - yarn test
  branches:
      master:
        - step:
            script:
              - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
              - export PATH=$HOME/.yarn/bin:$PATH
              - yarn
              - yarn test
              - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git